### ISSUE TITLE
rosdep 0.19.0 fails

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#93]
```
[INFO] ros_get.commands: rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Traceback (most recent call last):
  File "/usr/local/bin/ros-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ros_get/__main__.py", line 161, in main
    return func(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/ros_get/commands.py", line 44, in update
    exit_code = command_update(Namespace(include_eol_distros=False))
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 649, in command_update
    ros_distro=options.ros_distro)
AttributeError: 'Namespace' object has no attribute 'ros_distro'
```

**Comment by reinzor** [comment]
Will be captured by upcoming nightly build. For now we downgraded to `0.18.0` of `rosdep`, this still seems to work.

**Comment by Rayman** [comment]
Issue was introduced by https://github.com/ros-infrastructure/rosdep/pull/738
